"""Add expected_delivery_date to Order model

Revision ID: 00ed138a48f8
Revises: ba8551b36b89
Create Date: 2025-06-08 07:17:42.740713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ed138a48f8'
down_revision = 'ba8551b36b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('expected_delivery_date')

    # ### end Alembic commands ###
