"""empty message

Revision ID: 1aacc162dc66
Revises: b03310994627
Create Date: 2025-05-07 07:28:50.903482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aacc162dc66'
down_revision = 'b03310994627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_carrier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('tracking_carrier')

    # ### end Alembic commands ###
