"""Add GTIN and MPN fields to Asset model for price comparison

Revision ID: 24bc05330d18
Revises: 444634b580b2
Create Date: 2025-10-05 20:00:26.148273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bc05330d18'
down_revision = '444634b580b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gtin', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('manufacturer_part_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('manufacturer_part_number')
        batch_op.drop_column('gtin')

    # ### end Alembic commands ###
