"""Add inventory_session_id to CalendarEvent

Revision ID: 444634b580b2
Revises: db421d9c364f
Create Date: 2025-10-03 14:47:57.957668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444634b580b2'
down_revision = 'db421d9c364f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_event_inventory_session', 'inventory_planning', ['inventory_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_event_inventory_session', type_='foreignkey')
        batch_op.drop_column('inventory_session_id')

    # ### end Alembic commands ###
