"""Add location_id to Asset

Revision ID: 554a93903801
Revises: 20250419_rename_orderitem_serial_number
Create Date: 2025-04-20 06:30:01.715903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554a93903801'
down_revision = '20250419_rename_orderitem_serial_number'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_asset_location_id', 'location', ['location_id'], ['id'])
        batch_op.drop_column('seriennummer')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seriennummer', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
