"""Add expected_quantity to InventoryItem

Revision ID: 5afe956f1fe1
Revises: b891b92e9038
Create Date: 2025-04-25 14:06:00.166700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afe956f1fe1'
down_revision = 'b891b92e9038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('expected_quantity')

    # ### end Alembic commands ###
