"""Add tracking_carrier to Order

Revision ID: 7f1f4332443f
Revises: b018533a43fb
Create Date: 2025-05-06 16:23:19.970241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1f4332443f'
down_revision = 'b018533a43fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_carrier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('tracking_carrier')

    # ### end Alembic commands ###
