"""Add pdf_path column to Order model

Revision ID: 818af458ec3f
Revises: 00ed138a48f8
Create Date: 2025-06-16 12:45:04.923202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818af458ec3f'
down_revision = '00ed138a48f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
