"""Add serial_statuses to InventoryItem

Revision ID: b018533a43fb
Revises: 5afe956f1fe1
Create Date: 2025-04-27 01:20:39.313247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b018533a43fb'
down_revision = '5afe956f1fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_statuses', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('serial_statuses')

    # ### end Alembic commands ###
