"""Add cc_emails field to Order model

Revision ID: b4e33ec96f64
Revises: 818af458ec3f
Create Date: 2025-06-18 15:33:52.515941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4e33ec96f64'
down_revision = '818af458ec3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cc_emails', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cc_emails')

    # ### end Alembic commands ###
