"""Add inventory fields to Location model

Revision ID: ba8551b36b89
Revises: e000d00c154a
Create Date: 2025-06-06 06:53:43.732240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8551b36b89'
down_revision = 'e000d00c154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_inventory_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('inventory_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('inventory_status')
        batch_op.drop_column('last_inventory_date')

    # ### end Alembic commands ###
