"""Add signature and PDF fields to Loan model

Revision ID: db421d9c364f
Revises: 
Create Date: 2025-10-02 13:01:50.859270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db421d9c364f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_return_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('signature_employer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')
        batch_op.drop_column('pdf_filename')
        batch_op.drop_column('signature_employer')
        batch_op.drop_column('signature')
        batch_op.drop_column('actual_return_date')

    # ### end Alembic commands ###
