"""Add location_id to Order and migrate data

Revision ID: f8b1a1fb5800
Revises: 554a93903801
Create Date: 2025-04-20 10:34:26.913381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b1a1fb5800'
down_revision = '554a93903801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_location_id', 'location', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_location_id', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
